FROM ubuntu:bionic
LABEL MAINTAINER chrisbloemker@gmail.com

RUN apt update; \
    apt install vim-common -y

RUN apt install -y openssh-server
RUN mkdir /var/run/sshd

# This is only for testing purposes
RUN echo 'root:password' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]